CREATE TABLE task_list (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    creator_id BIGSERIAL NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);